#!/usr/bin/env bash
# =============================================================================
# init_repo.sh - Create the NT219 PQC project directory tree (idempotent).
# Run from the repository root:   bash scripts/init_repo.sh
# Or target another dir:          bash init_repo.sh /path/to/repo
# =============================================================================
set -eu
ROOT="${1:-.}"
cd "$ROOT"

# --- Directories (each maps to a concern / Work Package) ---------------------
mkdir -p \
  src \
  build \
  scripts \
  benchmarks/micro \
  benchmarks/tls \
  benchmarks/energy \
  data/raw/x86_64 \
  data/raw/aarch64 \
  tools \
  analysis_out \
  cmake \
  docker \
  docs

# --- Keep otherwise-empty dirs tracked in git --------------------------------
for d in build benchmarks/micro benchmarks/tls benchmarks/energy \
         data/raw/x86_64 data/raw/aarch64 analysis_out cmake docker docs; do
  [ -e "$d/.gitkeep" ] || touch "$d/.gitkeep"
done

# --- .gitignore (create only if missing; never overwrite) --------------------
if [ ! -f .gitignore ]; then
  cat > .gitignore << 'GI'
# Build artifacts (regenerated by `make`)
/build/
*.o
# Generated analysis output (regenerated by tools/analyze.py)
/analysis_out/
# Private keys / secrets -- NEVER commit these
*.key
*-prv.pem
*.srl
# Editor / OS noise
*.swp
.DS_Store
GI
  echo "Created .gitignore"
fi

echo "Directory tree ready under: $(pwd)"
